version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    command: python ./converter/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
